line-length = 88
target-version = "py312"

[lint]
select = [
  "E",    # pycodestyle (errors)
  "F",    # pyflakes
  "B",    # bugbear (code smells)
  "I",    # isort (import sorting)
  "C90",  # McCabe complexity
  "RUF",  # Ruff-specific rules
]
fixable = ["ALL"]
