// This file is auto-generated by @hey-api/openapi-ts

/**
 * GetExpiriesResponse
 */
export type GetExpiriesResponse = {
    /**
     * Expiries
     */
    expiries: Array<string>;
};

/**
 * GetExpiryResponse
 */
export type GetExpiryResponse = {
    /**
     * Options
     */
    options: Array<OptionData>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * OptionData
 */
export type OptionData = {
    /**
     * Underlying
     */
    underlying: string;
    /**
     * Contract
     */
    contract: string;
    /**
     * Expiry
     */
    expiry: string;
    /**
     * Strike
     */
    strike: number;
    /**
     * Kind
     */
    kind: string;
    /**
     * Bid
     */
    bid: number;
    /**
     * Ask
     */
    ask: number;
    /**
     * Oi
     */
    oi: number;
    /**
     * Iv
     */
    iv: number;
    /**
     * Timestamp
     */
    timestamp: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetExpiriesData = {
    body?: never;
    path: {
        /**
         * Ticker
         */
        ticker: string;
    };
    query?: never;
    url: '/api/v1/tickers/{ticker}/expiries';
};

export type GetExpiriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetExpiriesError = GetExpiriesErrors[keyof GetExpiriesErrors];

export type GetExpiriesResponses = {
    /**
     * Successful Response
     */
    200: GetExpiriesResponse;
};

export type GetExpiriesResponse2 = GetExpiriesResponses[keyof GetExpiriesResponses];

export type GetExpiryData = {
    body?: never;
    path: {
        /**
         * Ticker
         */
        ticker: string;
        /**
         * Expiry
         */
        expiry: string;
    };
    query?: never;
    url: '/api/v1/tickers/{ticker}/expiries/{expiry}';
};

export type GetExpiryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetExpiryError = GetExpiryErrors[keyof GetExpiryErrors];

export type GetExpiryResponses = {
    /**
     * Successful Response
     */
    200: GetExpiryResponse;
};

export type GetExpiryResponse2 = GetExpiryResponses[keyof GetExpiryResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};