// This file is auto-generated by @hey-api/openapi-ts

/**
 * GetOptionsResponse
 */
export type GetOptionsResponse = {
    /**
     * Expiries
     */
    expiries: Array<string>;
    /**
     * Expiry
     */
    expiry: string;
    /**
     * Options
     */
    options: Array<OptionData>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * OptionData
 */
export type OptionData = {
    /**
     * Underlying
     */
    underlying: string;
    /**
     * Contract
     */
    contract: string;
    /**
     * Expiry
     */
    expiry: string;
    /**
     * Strike
     */
    strike: number;
    /**
     * Kind
     */
    kind: string;
    /**
     * Bid
     */
    bid: number;
    /**
     * Ask
     */
    ask: number;
    /**
     * Oi
     */
    oi: number | null;
    /**
     * Iv
     */
    iv: number;
    /**
     * Timestamp
     */
    timestamp: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetOptionsData = {
    body?: never;
    path: {
        /**
         * Ticker
         */
        ticker: string;
    };
    query?: {
        /**
         * Expiry
         */
        expiry?: string | null;
    };
    url: '/api/v1/tickers/{ticker}/options';
};

export type GetOptionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOptionsError = GetOptionsErrors[keyof GetOptionsErrors];

export type GetOptionsResponses = {
    /**
     * Successful Response
     */
    200: GetOptionsResponse;
};

export type GetOptionsResponse2 = GetOptionsResponses[keyof GetOptionsResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};