// This file is auto-generated by @hey-api/openapi-ts

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetExpiriesApiV1TickersTickerExpiriesGetData = {
    body?: never;
    path: {
        /**
         * Ticker
         */
        ticker: string;
    };
    query?: never;
    url: '/api/v1/tickers/{ticker}/expiries';
};

export type GetExpiriesApiV1TickersTickerExpiriesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetExpiriesApiV1TickersTickerExpiriesGetError = GetExpiriesApiV1TickersTickerExpiriesGetErrors[keyof GetExpiriesApiV1TickersTickerExpiriesGetErrors];

export type GetExpiriesApiV1TickersTickerExpiriesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetExpiryApiV1TickersTickerExpiriesExpiryGetData = {
    body?: never;
    path: {
        /**
         * Ticker
         */
        ticker: string;
        /**
         * Expiry
         */
        expiry: string;
    };
    query?: never;
    url: '/api/v1/tickers/{ticker}/expiries/{expiry}';
};

export type GetExpiryApiV1TickersTickerExpiriesExpiryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetExpiryApiV1TickersTickerExpiriesExpiryGetError = GetExpiryApiV1TickersTickerExpiriesExpiryGetErrors[keyof GetExpiryApiV1TickersTickerExpiriesExpiryGetErrors];

export type GetExpiryApiV1TickersTickerExpiriesExpiryGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};