/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TickersTickerIndexRouteImport } from './routes/tickers/$ticker/index'
import { Route as TickersTickerExpiriesExpiryIndexRouteImport } from './routes/tickers/$ticker/expiries/$expiry/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TickersTickerIndexRoute = TickersTickerIndexRouteImport.update({
  id: '/tickers/$ticker/',
  path: '/tickers/$ticker/',
  getParentRoute: () => rootRouteImport,
} as any)
const TickersTickerExpiriesExpiryIndexRoute =
  TickersTickerExpiriesExpiryIndexRouteImport.update({
    id: '/tickers/$ticker/expiries/$expiry/',
    path: '/tickers/$ticker/expiries/$expiry/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tickers/$ticker': typeof TickersTickerIndexRoute
  '/tickers/$ticker/expiries/$expiry': typeof TickersTickerExpiriesExpiryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tickers/$ticker': typeof TickersTickerIndexRoute
  '/tickers/$ticker/expiries/$expiry': typeof TickersTickerExpiriesExpiryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tickers/$ticker/': typeof TickersTickerIndexRoute
  '/tickers/$ticker/expiries/$expiry/': typeof TickersTickerExpiriesExpiryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tickers/$ticker' | '/tickers/$ticker/expiries/$expiry'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tickers/$ticker' | '/tickers/$ticker/expiries/$expiry'
  id:
    | '__root__'
    | '/'
    | '/tickers/$ticker/'
    | '/tickers/$ticker/expiries/$expiry/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TickersTickerIndexRoute: typeof TickersTickerIndexRoute
  TickersTickerExpiriesExpiryIndexRoute: typeof TickersTickerExpiriesExpiryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickers/$ticker/': {
      id: '/tickers/$ticker/'
      path: '/tickers/$ticker'
      fullPath: '/tickers/$ticker'
      preLoaderRoute: typeof TickersTickerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickers/$ticker/expiries/$expiry/': {
      id: '/tickers/$ticker/expiries/$expiry/'
      path: '/tickers/$ticker/expiries/$expiry'
      fullPath: '/tickers/$ticker/expiries/$expiry'
      preLoaderRoute: typeof TickersTickerExpiriesExpiryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TickersTickerIndexRoute: TickersTickerIndexRoute,
  TickersTickerExpiriesExpiryIndexRoute: TickersTickerExpiriesExpiryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
