/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TickersTickerOptionsRouteImport } from './routes/tickers/$ticker/options'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TickersTickerOptionsRoute = TickersTickerOptionsRouteImport.update({
  id: '/tickers/$ticker/options',
  path: '/tickers/$ticker/options',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tickers/$ticker/options': typeof TickersTickerOptionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tickers/$ticker/options': typeof TickersTickerOptionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tickers/$ticker/options': typeof TickersTickerOptionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tickers/$ticker/options'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tickers/$ticker/options'
  id: '__root__' | '/' | '/tickers/$ticker/options'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TickersTickerOptionsRoute: typeof TickersTickerOptionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickers/$ticker/options': {
      id: '/tickers/$ticker/options'
      path: '/tickers/$ticker/options'
      fullPath: '/tickers/$ticker/options'
      preLoaderRoute: typeof TickersTickerOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TickersTickerOptionsRoute: TickersTickerOptionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
